service: mr_wet_test
image: mr_wet_test

servers:
  web:
    - 127.0.0.1

# registry:
#   username: dummy
#   password:
#     - DUMMY_PASSWORD

env:
  secret:
    - RAILS_MASTER_KEY

builder:
  arch: amd64

aliases:
  logs: app logs -f

volumes:
  - "mr_wet_test_storage:/rails/storage"
