# Name of your application. Used to uniquely configure containers.
service: mr_wet_test

# Name of the container image.
image: your-user/mr_wet_test

# Deploy to your local machine (or a free server). If using local, you can leave this as is.
servers:
  web:
    - 127.0.0.1

# If you don’t have an external proxy setup, you can remove or comment out the proxy block:
# proxy:
#   ssl: true
#   host: app.example.com

# Credentials for your image host.
registry:
  username: your-user
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  secret:
    - RAILS_MASTER_KEY
  clear:
    SOLID_QUEUE_IN_PUMA: true

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole"

volumes:
  - "mr_wet_test_storage:/rails/storage"

asset_path: /rails/public/assets

builder:
  arch: amd64
